Vagrant.configure(2) do |config|
  config.vm.box = 'gce'

  config.vm.provider :google do |google, override|
    google.google_project_id = 'k0kubun-isucon5'
    google.google_client_email = ENV['SERVICE_ACCOUNT_EMAIL_ADDRESS']
    google.google_json_key_location = '~/k0kubun-isucon5.json'

    # the same spec as m3.xlarge
    google.machine_type = 'n1-standard-4'
    google.image = 'ubuntu-1404-trusty-v20150909a'
    google.zone  = 'asia-east1-c'

    # override.ssh.host = '104.155.238.208'
    override.ssh.username = 'takashi-kokubun'
    override.ssh.private_key_path = '~/.ssh/google_compute_engine'
  end
end
