Vagrant.configure(2) do |config|
  config.vm.box = "gentoo-amd4"
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/mfurnvstqoj8w47/gentoo-20131024-amd64-minimal.box"

  config.vm.provision "shell", path: "../pubkey.sh"
end
