language: ruby
cache: bundler
sudo: false
dist: trusty
script:
- true
matrix:
  include:
    - rvm: 2.5.7
# notifications:
#   webhooks:
#     urls:
#       secure: xxx
#     on_build_success: false
#     on_build_failure: true
#     on_build_status_changed: false
