Vagrant.configure(2) do |config|
  config.vm.box = "fedora-20"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-20_chef-provisionerless.box"

  config.vm.provision "shell", path: "../pubkey.sh"
end
