#!/bin/bash -e

version="$1"
if [ -z $1 ]; then
  echo "usage: llvm-download [version]"
  echo "http://releases.llvm.org/download.html"
  exit 1
fi

mkdir -p "${HOME}/.llvmenv/archives"
mkdir -p "${HOME}/.llvmenv/src"

function download() {
  local url="$1"
  local path="$2"
  if [ ! -f "$path" ]; then
    echo "downloading from ${url} to ${path}..."
    wget "$url" -O "$path"
  fi
}
download "http://releases.llvm.org/${version}/llvm-${version}.src.tar.xz"        "${HOME}/.llvmenv/archives/llvm-${version}.tar.xz"
download "http://releases.llvm.org/${version}/cfe-${version}.src.tar.xz"         "${HOME}/.llvmenv/archives/cfe-${version}.tar.xz"
download "http://releases.llvm.org/${version}/compiler-rt-${version}.src.tar.xz" "${HOME}/.llvmenv/archives/compiler-rt-${version}.tar.xz"
download "http://releases.llvm.org/${version}/libcxx-${version}.src.tar.xz"      "${HOME}/.llvmenv/archives/libcxx-${version}.tar.xz"
download "http://releases.llvm.org/${version}/libcxxabi-${version}.src.tar.xz"   "${HOME}/.llvmenv/archives/libcxxabi-${version}.tar.xz"

function extract() {
  local xz_path="$1"
  local tar_path="$2"
  local src_path="$3"
  local dest_path="$4"

  if [ ! -d "$dest_path" ]; then
    echo "extracting from ${xz_path} to ${dest_path}..."
    pushd "${HOME}/.llvmenv/archives" > /dev/null
    xz -dk "$xz_path"
    tar xf "$tar_path"
    mv "${src_path}" "${dest_path}"
    popd > /dev/null
  fi
}
extract "llvm-${version}.tar.xz"        "llvm-${version}.tar"        "llvm-${version}.src"        "${HOME}/.llvmenv/src/llvm-${version}"
extract "cfe-${version}.tar.xz"         "cfe-${version}.tar"         "cfe-${version}.src"         "${HOME}/.llvmenv/src/llvm-${version}/tools/clang"
extract "compiler-rt-${version}.tar.xz" "compiler-rt-${version}.tar" "compiler-rt-${version}.src" "${HOME}/.llvmenv/src/llvm-${version}/projects/compiler-rt"
extract "libcxx-${version}.tar.xz"      "libcxx-${version}.tar"      "libcxx-${version}.src"      "${HOME}/.llvmenv/src/llvm-${version}/projects/libcxx"
extract "libcxxabi-${version}.tar.xz"   "libcxxabi-${version}.tar"   "libcxxabi-${version}.src"   "${HOME}/.llvmenv/src/llvm-${version}/projects/libcxxabi"
