#!/bin/bash -e

version="$1"
if [ -z $1 ]; then
  echo "usage: llvm-dbuild [version]"
  echo "http://releases.llvm.org/download.html"
  exit 1
fi

here="$(cd "$(dirname $0)"; pwd)"
"$here/llvm-download" "${version}"

mkdir -p "${HOME}/.llvmenv/debug-build/${version}"
mkdir -p "${HOME}/.llvmenv/debug-versions/${version}"

pushd "${HOME}/.llvmenv/debug-build/${version}" > /dev/null

"../../src/llvm-${version}/configure" "--prefix=${HOME}/.llvmenv/debug-versions/${version}" --disable-optimized --enable-assertions --enable-debug-runtime --enable-debug-symbols
make -j4
make install

popd > /dev/null
