#!/bin/bash -e

version="$1"
if [ -z $1 ]; then
  echo "usage: llvm-build [version]"
  echo "http://releases.llvm.org/download.html"
  exit 1
fi

here="$(cd "$(dirname $0)"; pwd)"
"$here/llvm-download" "${version}"

mkdir -p "${HOME}/.llvmenv/build/${version}"
mkdir -p "${HOME}/.llvmenv/versions/${version}"

pushd "${HOME}/.llvmenv/build/${version}" > /dev/null

cmake -G "Unix Makefiles" "-DCMAKE_INSTALL_PREFIX=${HOME}/.llvmenv/versions/${version}" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=No "../../src/llvm-${version}"
make -j4
make install

popd > /dev/null
