source 'https://rubygems.org'

gem 'rails', '>= 5.0.0.beta1', '< 5.1'
gem 'sqlite3'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'sprockets', github: 'rails/sprockets'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'puma'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 3.0'
  gem 'spring'
end
