FROM ubuntu:18.04
MAINTAINER k0kubun

# apt-get update
# apt install gcc
# apt install wget
# wget https://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
# tar xvzf gcc-7.4.0.tar.gz
# apt install libgmp-dev
# apt install libmpfr-dev
# apt install libmpc-dev
# apt install make

# wget https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.15.tar.gz
# tar xvzf linux-4.15.tar.gz
# cd linux-4.15.tar.gz

# mkdir /opt/cross-gcc

# wget https://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.gz
# tar xvzf binutils-2.30.tar.gz


# ./configure --build=x86_64-linux --host=x86_64-linux --target=sparc-sun-solaris2.10
# make -j4
