name: macos
on: [push]
jobs:
  latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configure: [default]
        include:
          - test_task: test1
          - test_task: test2
            configure: override
      fail-fast: false
    steps:
      - run: echo ${{ matrix.test_task }} ${{ matrix.configure }}
      #- name: clone
      #  run: |
      #    git clone --depth=1 https://github.com/k0kubun/misc .

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      #- name: Dump strategy context
      #  env:
      #    STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      #  run: echo "$STRATEGY_CONTEXT"

      #- name: Dump matrix context
      #  env:
      #    MATRIX_CONTEXT: ${{ toJson(matrix) }}
      #  run: echo "$MATRIX_CONTEXT"
      #  if: failure()

      #- name: Dump job context
      #  env:
      #    JOB_CONTEXT: ${{ toJson(job) }}
      #  run: echo "$JOB_CONTEXT"
      #  if: failure()

      #- name: Dump runner context
      #  env:
      #    RUNNER_CONTEXT: ${{ toJson(runner) }}
      #  run: echo "$RUNNER_CONTEXT"

      #- name: Dump steps context
      #  env:
      #    STEPS_CONTEXT: ${{ toJson(steps) }}
      #  run: echo "$STEPS_CONTEXT"

      #- uses: k0kubun/action-slack@v2.0.0
      #  with:
      #    payload: |
      #      {
      #        "attachments": [{
      #          "text": "${{ job.status}}: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.workflow }} / ${{ matrix.test_task }}> " +
      #                  "(<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|" + "${{ github.sha }}".substring(0, 10) + ">) " +
      #                  "of ${{ github.repository }}@" + "${{ github.ref }}".split('/').reverse()[0] + " by ${{ github.event.head_commit.committer.name }}",
      #          "color": "danger"
      #        }]
      #      }
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #  if: failure() && github.event_name == 'push'
  notify:
    runs-on: ubuntu-latest
    needs: latest
    steps:
      - name: hello
        run: echo hello
